name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'
          cache: maven
          
      - name: Step 3 - Install dependencies
        run: mvn dependency:resolve
        
      - name: Step 4 - Build Test
        run: mvn --file pom.xml -DtestEnvVariables='env.dev.properties' -DtestUsername='${{secrets.TEST_EMAIL}}' -DtestPassword='${{secrets.TEST_PW}}' -DloginSpec='test-suite/testsuite.xml' test
        
      - name: Step 5 - Download artifacts
        uses: actions/upload-artifact@v3
        with:
           name: upload-screen-recording
           path: captures/video/
      
