name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'
          cache: maven
          
      - name: Step 3 - Install dependencies
        run: mvn --batch-mode --update-snapshots package
        
      - name: Step 4 - Build Test
        run: mvn --file pom.xml -DtestEnvVariables='env.dev.properties' -DtestUsername='${{secrets.TEST_EMAIL}}' -DtestPassword='${{secrets.TEST_PW}}' -DloginSpec='test-suite/login_spec.xml' -DcheckoutSpec='test-suite/checkout_spec.xml' clean test
      
