name: CI

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2
        
      - name: Step 2 - Set up JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.9
      - name: Step 3 - Build Test
        run: mvn -f pom.xml -DtestEnvVariables='env.dev.properties' -DtestUsername=$TEST_EMAIL -DtestPassword=$TEST_PW -DloginSpec='test-suite/login_spec.xml' -DcheckoutSpec='test-suite/checkoutSpec.xml' clean test
        env:
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}
          TEST_PW: $ {{ secrets.TEST_PW }}
      - name: Step 4 - List the current directory
        run: ls- a
