name: CI
on:
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v4  # Changed from download-artifact to checkout
        
      - name: Step 2 - Set up JDK 19
        uses: actions/setup-java@v4  # Updated to v4
        with:
          java-version: '19'
          distribution: 'temurin'  # Added required distribution
          cache: maven
          
      - name: Step 3 - Install dependencies
        run: mvn dependency:resolve
        
      - name: Step 4 - Build Test
        run: mvn --file pom.xml -DtestEnvVariables='env.dev.properties' -DtestUsername='${{secrets.TEST_EMAIL}}' -DtestPassword='${{secrets.TEST_PW}}' -DloginSpec='test-suite/testsuite.xml' clean test
        
      - name: Step 5 - Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4  # Changed to upload-artifact
        with:
           name: upload-captures
           path: ./captures/
